52 atividades
fga-eps-mds/2020.1-Minacademy-BackEnd pull request #8
Opened 2020-09-25 22:42 UTC by peHaick

# Issue 52 - Atividades

## Descrição

Tem o objetivo de implementar a funcionalidade de atividades para serem feitas após o tutorial, assim como a criação dessas atividades.

## Issue Relacionada

#52

## Como isso foi testado?

- [x] Testes unitários
- [ ] Teste exploratório
- [ ] Não aplicável

## Imagens (se aplicável)

![52-atividades](https://user-images.githubusercontent.com/57498006/94321805-165b0680-ff67-11ea-822f-9d5404d66fa6.png)

## Essa modificação exige atualização da documentação?

Não

## Tipo de alteração

- [x] Nova feature
- [ ] Correção de bugs
- [ ] Alteração de uma funcionalidade já existente
- [ ] Documentação

2020-09-26 00:29 UTC, GeovanaRamos requested changes
Formalizando o review:
1. Não vejo todas as models do der necessárias para resolver a story. Como a aplicação guarda o que cada usuário respondeu? 
2. Um dos testes não possui a conexão com com o mongo in memory.
3. Muitas configurações do projeto foram mexidas de forma incorreta. Foi necessário para a implementação?

2020-09-26 00:31 UTC, GeovanaRamos commented on server/app.js
> +    "http://localhost:3000"
url hardcoded, usamos env. Essa alteração é necessária?

2020-09-26 00:32 UTC, GeovanaRamos commented on server/package.json
> +  "jest": {
Isso quebra os testes no github. Vide https://www.npmjs.com/package/@shelf/jest-mongodb

2020-09-26 00:33 UTC, GeovanaRamos requested changes

2020-09-26 00:33 UTC, GeovanaRamos commented on server/tests/module.test.js
> +
Pode ser que isso tbm quebre no github, pois não tem o mongo.

2020-09-26 01:03 UTC, EduardoPicolo commented on server/app.js
> +    "http://localhost:3000"
Sim, sem essa alteração os cookies nao funcionam, logo o login quebra.

2020-10-03 12:43 UTC, GeovanaRamos approved these changes

2020-10-03 12:47 UTC, merged